# Copyright (c) 2023 Hewlett Packard Enterprise Development LP

FROM rockylinux:9.0-minimal AS build

# Set Mellanox MFT version and platform
ENV MFT_VERS mft-4.23.0-104
ENV PLATFORM x86_64

# Base configuration
RUN microdnf clean all && \
    microdnf makecache && \
    microdnf --assumeyes install tar wget perl kmod file findutils iproute libcrypt libpcap && \
    microdnf clean all

# Infiniband libraries and utilities
RUN microdnf clean all && \
    microdnf makecache && \
    microdnf --assumeyes install rdma-core infiniband-diags libibverbs-utils && \
    microdnf clean all

# Mellanox firmware management tools
RUN wget https://www.mellanox.com/downloads/MFT/${MFT_VERS}-${PLATFORM}-rpm.tgz && \
	tar -xzf ${MFT_VERS}-${PLATFORM}-rpm.tgz && \
	rpm -i ${MFT_VERS}-${PLATFORM}-rpm/RPMS/${MFT_VERS}.${PLATFORM}.rpm && \
	rm -rf ${MFT_VERS}-${PLATFORM}-rpm

CMD ["/bin/bash"]
