apiVersion: v1
kind: Namespace
metadata:
  name: admin-privileged
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest

---

apiVersion: v1
kind: Pod
metadata:
  name: infiniband-admin
  namespace: admin-privileged
spec:
  hostNetwork: true
  containers:
    - name: infiniband-admin
      image: ghcr.io/<YOUR_GITHUB_USERID>/mesa-mofed-utils:5.9-0.5.6.0
      imagePullPolicy: IfNotPresent
      command:
        - "sleep"
        - "86400"
      volumeMounts:
        - mountPath: /sys
          name: host-sys
        - mountPath: /dev
          name: host-dev
        - mountPath: /lib/modules
          name: host-modules
          readOnly: true
      securityContext:
        capabilities:
          add:
          - SYS_RAWIO
          - SYS_ADMIN
        privileged: true
  securityContext:
    fsGroup: 0
    runAsGroup: 0
    runAsUser: 0

  volumes:
   - name: host-sys
     hostPath:
       path: /sys
       type: Directory
   - name: host-dev
     hostPath:
       path: /dev
       type: Directory
   - name: host-modules
     hostPath:
       path: /lib/modules
       type: Directory
